[package]
name = "cryptose"
version = "1.0.0"
authors = ["VexPlayzGH"]
edition = "2024"
description = "A library for effortlessly encrypting and decrypting messages."
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
